name: Deploy MultiDocker
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#      - run: docker build -t kc114414/react-test -f ./Dockerfile.dev .
#      - run: docker run -e CI=true kc114414/react-test npm test
 
      - run: docker build -t kc114414/multi-client-10-14 ./client
      - run: docker build -t kc114414/multi-nginx-10-14 ./nginx
      - run: docker build -t kc114414/multi-server-10-14 ./server
      - run: docker build -t kc114414/multi-worker-10-14 ./worker
 
      - run: docker push kc114414/multi-client-10-14
      - run: docker push kc114414/multi-nginx-10-14
      - run: docker push kc114414/multi-server-10-14
      - run: docker push kc114414/multi-worker-10-14
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: MultiDocker-env
          existing_bucket_name: elasticbeanstalk-us-west-2-474824339380
          bucket_path: docker-multi
          region: us-west-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
